### PR TITLE
Remove example mixin and rename mixins config file

### PR DESCRIPTION
**Pull request by jaydevelopsshit**
Title says it all, was really bugging me.

Also update to 1.16.5 and change some pretty retarded things to make everything look better.

### CODE REVIEW

**Comment by jaydevelopsshit** [comment]
Dude, just be alive.

**Comment by E404NNF** [comment]
Sorry I'm having irl issues, I'll look into it later, thanks for the PR anyways :)

**Comment by E404NNF** [comment]
I'll merge it for now

**Comment by jaydevelopsshit** [comment]
THANK YOU LMFAO

**Comment by jaydevelopsshit** [comment]
> Sorry I'm having irl issues, I'll look into it later, thanks for the PR anyways :)

I get that, and no problem

**Comment by E404NNF** [comment]
> > Sorry I'm having irl issues, I'll look into it later, thanks for the PR anyways :)
> 
> I get that, and no problem

i'm trying to be more and more active on github :D 

you can check my activity in this profile and at [cummodore69](https://github.com/cummodore69)

**Pull request merged**
